version: "3.8"
services:
  backend:
    image: "micleah/springboot-react-fullstack:22.7.2022.13.16.22"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev