version: "3.8"
services:
  backend:
    image: "micleah/springboot-react-fullstack:6.7.2022.11.26.1"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev